basic api fucntionality
SOEP-Group/SOEP pull request #10
Opened 2024-09-18 12:16 UTC by SuadHus

pleeeeasssee acceppppt

2024-09-20 05:21 UTC, mohammed-shakir requested changes
Some changes needed, but code looks good overall

2024-09-20 05:21 UTC, mohammed-shakir commented on CMakeLists.txt
> -file(GLOB_RECURSE SRC_FILES src/*.cpp)
dont remove this

2024-09-20 05:21 UTC, mohammed-shakir commented on CMakeLists.txt
> +add_executable(SOEP src/main.cpp)
compile the whole source tree

```
add_executable(SOEP ${SRC_FILES})
```

2024-09-20 05:21 UTC, mohammed-shakir commented on src/main.cpp
Dont add this code in main, create a seperate node that makes the API call

2024-09-20 05:38 UTC, mohammed-shakir commented on README.md
Add in the README, where to find the .env file

2024-09-20 05:41 UTC, mohammed-shakir commented on README.md
> +docker run --rm -e N2YO_API_KEY="<env_key>" soep
Add in the README, where to find the .env file

2024-09-20 05:55 UTC, syko240 reviewed
Is this for the whole [issue](https://github.com/SOEP-Group/SOEP/issues/2)?

Does not really align with what is described in the issue (create a networking module). My proposal: crate a generic API request functionality which returns the a buffer of the raw JSON string. Code messy, improve file structure or somthin.
like:
```
src/
    main.cpp
    (network/api) /
         api_call.h
         api_call.cpp
```
         
         
     
or something similar, up to repo owner
just please dont throw everything in main ?_?

2024-09-20 06:00 UTC, mohammed-shakir commented
> Is this for the whole [issue](https://github.com/SOEP-Group/SOEP/issues/2)?
> 
> Does not really align with what is described in the issue (create a networking module). My proposal: crate a generic API request functionality which returns the a buffer of the raw JSON string. Code messy, improve file structure or somthin. like:
> 
> ```
> src/
>     main.cpp
>     (network/api) /
>          api_call.h
>          api_call.cpp
> ```
> 
> or something similar idgaf, up to repo owner just please dont throw everything in main ?_?

yeah this structure that you suggested should be good enough for now. But the issue is a bit missleading, it was supposed to only be basic API call to fetch the into of 1 satellite (for now), and then @SuadHus was going to build upon that by creating more issues.

I suggest you (@SuadHus ) rewrite the issue to match what you have done and then create more issues for the rest of the functionallities mentioned in this issue.

@syko240 don't swear in your pr reviews 💀

2024-09-20 06:02 UTC, SuadHus commented
I didn't close the issue jusr pushed

2024-09-20 08:29 UTC, SuadHus commented on README.md
> +docker run --rm -e N2YO_API_KEY="<env_key>" soep
what??? Are you stupid?

2024-09-20 11:51 UTC, SuadHus commented
PLEASSSE ACCEPT

2024-09-20 22:55 UTC, syko240 reviewed
LG, just made one change.

2024-09-21 17:59 UTC, mohammed-shakir approved these changes
LGTM!

2024-09-21 17:59 UTC, merged