Refactor1
SOEP-Group/SOEP pull request #54
Opened 2024-11-07 19:27 UTC by syko240

Summery:
- Changed return types for db functions to return responses, better handling for exceptions
- Docker changes
- some other naming changes

2024-11-08 05:40 UTC, RyuTribal commented on Dockerfile
> +FROM ubuntu:22.04 AS builder
Very good, I think that is one of the most important changes that you've made

2024-11-08 05:46 UTC, RyuTribal requested changes
I like this so far. Good use of templated structs to handle errors instead of needless try and catches. 

THis whole thing of segmenting database functionality that belongs to one .h file across multiple .cpp files has to stop though. I never understood the point of it except that you have to jump around more files which takes longer than searching a bigger cpp file. For people who haven't worked on the code base looking in, it's hard to tell which of the files contain the function definition (which are all stored in one .h file). Please changes this. Hopping between files is usually more time consuming than looking at a bigger file

2024-11-08 05:49 UTC, RyuTribal commented
Or even better, just make a singleton type of header file for all the transactions that uses the db connection, just dont have multiple definitions spread across multiple cpp files. One header for one cpp file, thats the rule

2024-11-08 17:09 UTC, syko240 commented on Dockerfile
> +FROM ubuntu:22.04 AS builder
@RyuTribal upper case standard lil bro

2024-11-08 17:24 UTC, RyuTribal commented on Dockerfile
> +FROM ubuntu:22.04 AS builder
Bro I'm telling you, this change in code, literally changed my whole perception on life

2024-11-08 17:38 UTC, syko240 commented on Dockerfile
> +FROM ubuntu:22.04 AS builder
[I am wholeheartedly aligned, my spirit echoing with boundless affirmation, a conviction swelling beyond the measure of certainty—one hundred and one beats in favor of yours truly. For it is not mere agreement that I extend, but a vow, a commitment that stretches beyond words, as if the stars themselves nod in accord. My support is a river unending, flowing deeper and truer than numbers can ever capture, a testament to the faith that lives within.](https://tenor.com/view/funny-gif-23169978)

2024-11-08 17:41 UTC, syko240 commented
> I like this so far. Good use of templated structs to handle errors instead of needless try and catches.
> 
> THis whole thing of segmenting database functionality that belongs to one .h file across multiple .cpp files has to stop though. I never understood the point of it except that you have to jump around more files which takes longer than searching a bigger cpp file. For people who haven't worked on the code base looking in, it's hard to tell which of the files contain the function definition (which are all stored in one .h file). Please changes this. Hopping between files is usually more time consuming than looking at a bigger file

fair


> Or even better, just make a singleton type of header file for all the transactions that uses the db connection, just dont have multiple definitions spread across multiple cpp files. One header for one cpp file, thats the rule



I will look into it 👍

2024-11-08 17:41 UTC, mohammed-shakir commented on Dockerfile
> +FROM ubuntu:22.04 AS builder
Can you guys stfu?

2024-11-08 17:43 UTC, RyuTribal commented on Dockerfile
> +FROM ubuntu:22.04 AS builder
He is not seeing the light

2024-11-10 20:04 UTC, RyuTribal approved these changes
LGTM!

2024-11-11 13:10 UTC, mohammed-shakir commented
(i got tired, there are other places where it should be snake_case)

2024-11-11 14:23 UTC, syko240 commented
> (i got tired, there are other places where it should be snake_case)

sure, but I dont think it really matters, its more important to distinguish member variables from local or parameter variables.

2024-11-11 14:40 UTC, merged